service: serverless-text-generation-docker

provider:
  name: aws # provider
  region: us-east-1 # aws region
  memorySize: 5120 # optional, in MB, default is 1024
  timeout: 30 # optional, in seconds, default is 6

functions:
  questionanswering:
    image: <>.dkr.ecr.us-east-1.amazonaws.com/bert-lambda:bert-textgen-lambda #ecr url
    events:
      - http:
          path: textgen # http path
          method: post # http method
